---
internal_ip_eth1: 1.1.1.254
internal_ip_eth1_0: 1.1.1.253
public_port_rules:
  - name: smc http
    port: 10000
    target_ip: 1.1.1.9
    target_port: 80
  - name: smc_https
    port: 11000
    target_ip: 1.1.1.9
    target_port: 443
  - name: sns_websocket
    port: 12000
    target_ip: 1.1.1.9
    target_port: 1754
  - name: sns http
    port: 10001
    target_ip: 1.1.1.10
    target_port: 80
  - name: sns_https
    port: 11001
    target_ip: 1.1.1.10
    target_port: 443
  - name: cluster_http
    port: 10002
    target_ip: 1.1.1.11
    target_port: 80
  - name: cluster_https
    port: 11002
    target_ip: 1.1.1.11
    target_port: 443
internal_service_port_rules:
  - name: windows active direcory 2019 - No SSL
    port: 5000
    target_ip: 172.40.16.3
    target_port: 389
  - name: windows active direcory 2019 - With SSL
    port: 5001
    target_ip: 172.40.16.3
    target_port: 636
  - name: Cisco EST Server
    port: 5002
    target_ip: 172.40.16.11
    target_port: 8443
internal_service_ip_rules:
  - name: update1-sns.stormshieldcs.eu
    ip: 1.1.1.253
    target_ip: 149.202.36.4
    ports:
      - 80
      - 443

